services:
  postgres:
    image: postgres:16
    container_name: pgsql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  api:
    image: efaby10/my-api-service:latest
    build:
      context: ./src/ApiService/
      dockerfile: DockerFile
    ports:
      - "8080:8080"
    environment:
      - CorsOrigins=https://localhost
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=mydb;Username=postgres;Password=postgres
    depends_on:
      - postgres
  app:
    image: efaby10/my-blazor-app:latest
    build:
      context: ./src/Frontend/
      dockerfile: Dockerfile
    ports:
      - "8081:80"
      - "443:443"
    environment:
      - BaseUrl=http://localhost:8080
      - Authority=https://app-name.auth.region.amazoncognito.com
      - ClientId=xxxxxxxxx
      - RedirectUri=https://localhost/authentication/login-callback
      - PostLogoutRedirectUri=https://localhost/
      - MetadataUrl=https://domain-aws/pool_id/.well-known/openid-configuration
    depends_on:
      - api

volumes:
  pg_data: