server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki1:3100/loki/api/v1/push

scrape_configs:
  - job_name: otel-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: my-api
          service_name: my-api
          __path__: /var/log/otel/*.json