apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
  namespace: poc-blazor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
        - name: api-service
          image: ghcr.io/mushroomsoft-it/poc-blazor-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: CorsOrigins
              value: "*"
            - name: ConnectionStrings__DefaultConnection
              value: "Host=postgres.poc-blazor.svc.cluster.local;Port=5432;Database=pocblazordb;Username=postgres;Password=postgres123"
