apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: poc-blazor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: ghcr.io/mushroomsoft-it/poc-blazor-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: CorsOrigins
              value: "*"

            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: api-db-secret
                  key: DB_CONNECTION_STRING
