apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
data:
  init.sql: |
    -- Aquí tu contenido SQL
    CREATE TABLE IF NOT EXISTS Estudiantes (
        Id SERIAL PRIMARY KEY,
        Nombre TEXT,
        Direccion TEXT
    );
    INSERT INTO Estudiantes (Nombre, Direccion) VALUES ('Juan Perez', 'Calle Falsa 123');
