apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: observability
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: <ACCESS_KEY>
  AWS_SECRET_ACCESS_KEY: <SECRET_KEY>
  AWS_REGION: us-east-1
