name: Build and publish both Docker images

on:
  push:
    branches: ["eks-test"]

env:
  REGISTRY: ghcr.io
  # usaremos el owner del repo para formar las imágenes
  FRONTEND_IMAGE: ${{ github.repository_owner }}/poc-blazor-frontend
  API_IMAGE: ${{ github.repository_owner }}/poc-blazor-api

permissions:
  contents: read
  packages: write
  id-token: write # necesario para que el workflow que llame al deploy (via OIDC) pueda generar token si lo requiere

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # ---------- FRONTEND ----------
      - name: Build frontend
        run: docker build -t $REGISTRY/${FRONTEND_IMAGE}:latest ./src/Frontend

      - name: Push frontend
        run: docker push $REGISTRY/${FRONTEND_IMAGE}:latest

      # ---------- API ----------
      - name: Build api
        run: docker build -t $REGISTRY/${API_IMAGE}:latest ./src/ApiService

      - name: Push api
        run: docker push $REGISTRY/${API_IMAGE}:latest

  deploy:
    needs: build
    uses: ./.github/workflows/deploy-eks.yaml
    with:
      image_frontend: ghcr.io/${{ env.FRONTEND_IMAGE }}:latest
      image_api: ghcr.io/${{ env.API_IMAGE }}:latest
    secrets: inherit
