name: Build and publish Frontend Docker image
on:
  push:
    branches: ["enable-https"]
    paths:
      - "src/Frontend/**"
      - "k8s/frontend-*.yaml"
      - "k8s/ingress.yaml"
      - ".github/workflows/build-and-push-frontend.yaml"
      - ".github/workflows/deploy-frontend-eks.yaml"

env:
  REGISTRY: ghcr.io

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      frontend_image: ${{ steps.set_outputs.outputs.frontend_image }}

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build frontend
        run: |
          docker build -t $REGISTRY/${{ github.repository_owner }}/poc-blazor-frontend:${{ github.run_number }} ./src/Frontend

      - name: Push frontend
        run: |
          docker push $REGISTRY/${{ github.repository_owner }}/poc-blazor-frontend:${{ github.run_number }}
      - name: Set outputs
        id: set_outputs
        run: |
          echo "frontend_image=ghcr.io/${{ github.repository_owner }}/poc-blazor-frontend:${{ github.run_number }}" >> $GITHUB_OUTPUT

  deploy:
    needs: build
    uses: ./.github/workflows/deploy-frontend-eks.yaml
    with:
      image_frontend: ${{ needs.build.outputs.frontend_image }}
    secrets: inherit