name: Deploy both services to EKS

on:
  workflow_call:
    secrets:
      AWS_ACCOUNT_ID:
        required: true
    inputs:
      image_frontend:
        required: true
        type: string
      image_api:
        required: true
        type: string

  workflow_dispatch:
    inputs:
      image_frontend:
        description: "Frontend image tag for EKS"
        required: true
        default: "ghcr.io/mushroomsoft-it/poc-blazor-frontend:latest"
      image_api:
        description: "API image tag for EKS"
        required: true
        default: "ghcr.io/mushroomsoft-it/poc-blazor-api:latest"
permissions:
  id-token: write # necesario para OIDC -> asumir rol en AWS desde GitHub
  contents: read
  packages: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug
        run: |
          echo "Repo: $GITHUB_REPOSITORY"
          echo "Ref: $GITHUB_REF"

      - name: Configure AWS credentials (assume role via OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHub-Actions-Deploy-Role
          aws-region: us-east-1

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name eks-demo-cluster --region us-east-1

      - name: Ensure namespace exists
        run: |
          kubectl apply -f k8s/namespace.yaml

      - name: Ensure services & ingress are present (apply once)
        run: |
          kubectl apply -f k8s/api-service.yaml
          kubectl apply -f k8s/frontend-service.yaml
          kubectl apply -f k8s/ingress.yaml

      - name: Update frontend image (rolling update)
        run: |
          kubectl -n poc-blazor set image deployment/frontend frontend=${{ inputs.image_frontend }}
          kubectl -n poc-blazor rollout status deployment/frontend --timeout=120s

      - name: Update API image (rolling update)
        run: |
          kubectl -n poc-blazor set image deployment/api-service api-service=${{ inputs.image_api }}
          kubectl -n poc-blazor rollout status deployment/api-service --timeout=120s
