name: Build Full Solution

on:
  push:
    branches:
      - "!main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      # Ejecuta los tests con cobertura
      - name: Run Tests with Coverage
        run: |
          dotnet test \
            --no-build \
            --collect:"XPlat Code Coverage" \
            --results-directory ./coverage

      # Instalar el ReportGenerator
      - name: Install ReportGenerator
        run: dotnet tool install -g dotnet-reportgenerator-globaltool

      # Generar el Reporte HTML
      - name: Generate Coverage Report
        run: |
          reportgenerator \
            -reports:"coverage/**/coverage.cobertura.xml" \
            -targetdir:"coverage-report" \
            -reporttypes:Html

      # Guardar el artefacto con el reporte
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage-report
